//Our representation of the physical keyboard
enum keyboard_keys
{
    KB_NONE,
    
    KB_A,
   	KB_B,
   	KB_C,
   	KB_D,
   	KB_E,
   	KB_F,
   	KB_G,
   	KB_H,
   	KB_I,
   	KB_J,
   	KB_K,
   	KB_L,
   	KB_M,
    KB_N,
   	KB_O,
   	KB_P,
   	KB_Q,
   	KB_R,
   	KB_S,
   	KB_T,
   	KB_U,
   	KB_V,
   	KB_W,
   	KB_X,
   	KB_Y,
   	KB_Z,

    KB_SPACE,
   	KB_L_SHIFT,
   	KB_R_SHIFT,
   	KB_TAB,
   	KB_ENTER,
   	KB_LEFT,
   	KB_RIGHT,
   	KB_UP,
   	KB_DOWN,

    KB_L_CTRL,
   	KB_L_ALT,
   	KB_R_CTRL,
   	KB_R_ALT,
   	KB_DELETE,

   	KB_0,
   	KB_1,
   	KB_2,
   	KB_3,
   	KB_4,
   	KB_5,
   	KB_6,
   	KB_7,
   	KB_8,
   	KB_9,

    KB_ESCAPE,
   	KB_MINUS,
   	KB_EQUALS,
   	KB_QUOTE,
   	KB_SEMICOLON,
   	KB_FORWARD_SLASH,
   	KB_PERIOD,
   	KB_COMMA,
    
    KB_COUNT,
};

//Our concept of the game keys (this can obviously change as necessary)
//Make sure to change the string representation below as well if this is
//changed.  Also the KeyMapping.txt will need to change.
enum game_keys
{
    KEY_Left,
    KEY_Right,
    KEY_Up,
    KEY_Down,
    KEY_Action1,
    KEY_Action2,
    KEY_Action3,
    KEY_Action4,
    KEY_Action5,
    KEY_Action6,
    KEY_Select,
    KEY_Start,
    KEY_Shoulder1,
    KEY_Shoulder2,
    KEY_Shoulder3,
    KEY_Shoulder4,
    KEY_Quit,
    KEY_COUNT,
};

//We set up an array that will convert SDL Scancodes to our
//keyboard enum.  Maybe we could just map the scancodes themselves
//directly to the game keys, but this way seems nicer
void SetupSDLKeyToKeyboardEnumMapping();
void ParseKeymapConfig(const char *folder, const char *filename);

//String representations of the enums above (must be in the same order, or else the 
//string matching function in ParseKeymapConfig will not represent the correct value)
global_variable const char *KeyboardKeyStrings[] = 
{
    "KB_NONE",
    "KB_A",
	"KB_B",
	"KB_C",
	"KB_D",
	"KB_E",
	"KB_F",
	"KB_G",
	"KB_H",
	"KB_I",
	"KB_J",
	"KB_K",
	"KB_L",
	"KB_M",
    "KB_N",
	"KB_O",
	"KB_P",
	"KB_Q",
	"KB_R",
	"KB_S",
	"KB_T",
	"KB_U",
	"KB_V",
	"KB_W",
	"KB_X",
	"KB_Y",
	"KB_Z",
    "KB_SPACE",
	"KB_L_SHIFT",
	"KB_R_SHIFT",
	"KB_TAB",
	"KB_ENTER",
	"KB_LEFT",
	"KB_RIGHT",
	"KB_UP",
	"KB_DOWN",
    "KB_L_CTRL",
	"KB_L_ALT",
	"KB_R_CTRL",
	"KB_R_ALT",
	"KB_DELETE",
	"KB_0",
	"KB_1",
	"KB_2",
	"KB_3",
	"KB_4",
	"KB_5",
	"KB_6",
	"KB_7",
	"KB_8",
	"KB_9",
    "KB_ESCAPE",
	"KB_MINUS",
	"KB_EQUALS",
	"KB_QUOTE",
	"KB_SEMICOLON",
	"KB_FORWARD_SLASH",
	"KB_PERIOD",
	"KB_COMMA",
    "KB_COUNT",
};

global_variable const char *GameKeyStrings[] = 
{
    "KEY_Left",
    "KEY_Right",
    "KEY_Up",
    "KEY_Down",
    "KEY_Action1",
    "KEY_Action2",
    "KEY_Action3",
    "KEY_Action4",
    "KEY_Action5",
    "KEY_Action6",
    "KEY_Select",
    "KEY_Start",
    "KEY_Shoulder1",
    "KEY_Shoulder2",
    "KEY_Shoulder3",
    "KEY_Shoulder4",
    "KEY_Quit",
    "KEY_COUNT",
};
